import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CxNativeBridge, CxBridgeError } from "../src/bridge/cx-native-bridge.ts";
import { ProjectContextService } from "../src/project/project-context-service.ts";
import type { CliAdapter } from "../src/cli/types.ts";
import type { OrchestrationRequest, OrchestrationResult } from "../src/orchestration/types.ts";
import type { UsageSnapshot } from "../src/budget/types.ts";

const usage: UsageSnapshot = { source: "manual", capturedAt: "2026-09-07T00:00:00.000Z", fiveHour: { remainingPercent: 80 }, weekly: { remainingPercent: 70 } };
class Adapter implements CliAdapter {
  public usageCalls = 0; public executions: OrchestrationRequest[] = []; public failUsage = false; public failExecution = false; public unavailable = false; public escalation = false;
  public async getUsage(): Promise<UsageSnapshot> { this.usageCalls++; if (this.failUsage) throw new Error("unavailable"); return usage; }
  public async executeAuto(input: OrchestrationRequest): Promise<OrchestrationResult> { this.executions.push(input); if (this.failExecution) throw new Error("App Server unavailable"); const decision = input.routingDecision!; const finalStatus = this.unavailable ? "unavailable" : "success"; return { taskExecution: { id: "task", prompt: input.prompt, routingDecision: decision, threadId: this.unavailable ? null : "bridge-thread", createdAt: usage.capturedAt, updatedAt: usage.capturedAt, attempts: [], finalStatus: this.unavailable ? "not-executed" : "success" }, finalStatus, finalModel: this.unavailable ? null : decision.selectedModel, finalReasoning: this.unavailable ? null : decision.reasoning, totalAttempts: this.escalation ? 2 : 1, escalations: this.escalation ? [{ action: "escalate-model", currentModel: "terra", nextModel: "sol", nextReasoning: "medium", reason: "complex" }] : [], budgetDecisions: [], usageSnapshot: usage, budgetState: "balanced", executionBudget: { state: "balanced", reasoningCaps: {}, maxAttemptsPerModel: { luna: 2, terra: 2, sol: 1, astra: 1 }, maxTotalAttempts: 4, allowAutomaticEscalationToSol: true, allowAutomaticEscalationToAstra: true, reasons: [] }, stoppedReason: this.unavailable ? "Required model unavailable" : "done" }; }
  public async close(): Promise<void> {}
}
function workspace() { const cwd = mkdtempSync(join(tmpdir(), "cx-bridge-")); writeFileSync(join(cwd, "package.json"), JSON.stringify({ dependencies: { react: "1" } })); writeFileSync(join(cwd, ".env"), "SECRET=hidden"); writeFileSync(join(cwd, "reference.png"), "png"); return cwd; }

describe("CxNativeBridge", () => {
  it("routes through the shared engine without executing", async () => { const adapter = new Adapter(); const bridge = new CxNativeBridge({ cwd: workspace(), adapter }); const result = await bridge.route("Cambia el padding del navbar"); assert.equal(result.selectedModel, "luna"); assert.equal(adapter.executions.length, 0); });
  it("accepts explicit workspace image references without changing the base model", async () => { const cwd = workspace(), adapter = new Adapter(), bridge = new CxNativeBridge({ cwd, adapter }); const route = await bridge.route("Cambia el padding del navbar", [{ type: "image", path: "reference.png" }]); assert.equal(route.hasVisualContext, true); assert.equal(route.selectedModel, "luna"); await bridge.execute("Cambia el padding del navbar", [{ type: "image", path: "reference.png" }]); assert.equal(adapter.executions[0]?.attachments?.[0]?.name, "reference.png"); });
  it("returns controlled image-reference errors", async () => { await assert.rejects(() => new CxNativeBridge({ cwd: workspace(), adapter: new Adapter() }).route("Cambia padding", [{ type: "image", path: ".env" }]), /Unsupported|sensitive/); });
  it("reads status without starting a turn and handles usage failures", async () => { const adapter = new Adapter(); const bridge = new CxNativeBridge({ cwd: workspace(), adapter }); assert.equal((await bridge.status()).budget, "balanced"); assert.equal(adapter.executions.length, 0); adapter.failUsage = true; assert.equal((await bridge.status()).usage.source, "unknown"); });
  it("shares .cx with the CLI project service and keeps projects isolated", () => { const first = workspace(), second = workspace(); const adapter = new Adapter(); const bridge = new CxNativeBridge({ cwd: first, adapter }); const project = bridge.project(); const cliSnapshot = new ProjectContextService().open(first); assert.equal(project.metadata.projectId, cliSnapshot.metadata.projectId); assert.notEqual(project.metadata.projectId, new CxNativeBridge({ cwd: second, adapter }).project().metadata.projectId); });
  it("returns only compact, secret-free context", () => { const bridge = new CxNativeBridge({ cwd: workspace(), adapter: new Adapter() }); const text = JSON.stringify(bridge.context()); assert.equal(text.includes("SECRET"), false); assert.equal(text.includes(".env"), false); assert.ok(text.length < 4000); });
  it("executes with a compact context prompt, result and persisted CX thread", async () => { const cwd = workspace(), adapter = new Adapter(), bridge = new CxNativeBridge({ cwd, adapter }); const output = await bridge.execute("Implementa módulo de clientes con Supabase"); assert.match(adapter.executions[0]?.prompt ?? "", /^\[CX project context:/); assert.equal(output.result.threadId, "bridge-thread"); assert.equal(output.result.status, "success"); assert.equal(JSON.stringify(output.result).includes("taskExecution"), false); assert.equal(new ProjectContextService().open(cwd).threads.activeThreadId, "bridge-thread"); });
  it("reuses a valid CX thread without treating it as a host thread", async () => { const cwd = workspace(), adapter = new Adapter(), projects = new ProjectContextService(), snapshot = projects.open(cwd); snapshot.threads.activeThreadId = "cx-thread"; snapshot.threads.threads.push({ threadId: "cx-thread", createdAt: "now", lastUsedAt: "now", status: "active" }); projects.saveThreads(cwd, snapshot.threads); await new CxNativeBridge({ cwd, adapter }).execute("Cambia padding"); assert.equal(adapter.executions[0]?.threadId, "cx-thread"); });
  it("clears an invalid CX thread and surfaces model availability compactly", async () => { const cwd = workspace(), adapter = new Adapter(), projects = new ProjectContextService(), snapshot = projects.open(cwd); snapshot.threads.activeThreadId = "invalid-thread"; projects.saveThreads(cwd, snapshot.threads); adapter.unavailable = true; const output = await new CxNativeBridge({ cwd, adapter }).execute("Analiza pagos"); assert.equal(output.result.status, "unavailable"); assert.equal(projects.open(cwd).threads.activeThreadId, undefined); assert.match(output.result.summary, /unavailable/); });
  it("shows escalation paths without exposing internal execution logs", async () => { const adapter = new Adapter(); adapter.escalation = true; const output = await new CxNativeBridge({ cwd: workspace(), adapter }).execute("Problema complejo"); assert.deepEqual(output.result.escalations, ["terra → sol medium"]); assert.equal(JSON.stringify(output.result).includes("attempts"), true); });
  it("returns a controlled App Server execution error", async () => { const adapter = new Adapter(); adapter.failExecution = true; await assert.rejects(() => new CxNativeBridge({ cwd: workspace(), adapter }).execute("Cambia padding"), /CX execution unavailable/); });
  it("rejects an invalid plugin workspace before accessing project files", () => { assert.throws(() => new CxNativeBridge({ cwd: "", adapter: new Adapter() }), /valid workspace/); });
  it("returns controlled bridge errors for an empty task", async () => { await assert.rejects(() => new CxNativeBridge({ cwd: workspace(), adapter: new Adapter() }).route(""), CxBridgeError); });
});
