import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { mkdtempSync, mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { ProjectContextService } from "../src/project/project-context-service.ts";

function repo(git = true) { const path = mkdtempSync(join(tmpdir(), "cx-project-")); writeFileSync(join(path, "package.json"), JSON.stringify({ scripts: { test: "node --test" }, dependencies: { react: "1" } })); writeFileSync(join(path, "AGENTS.md"), "Use tests."); if (git) { execFileSync("git", ["init"], { cwd: path }); execFileSync("git", ["add", "."], { cwd: path }); execFileSync("git", ["-c", "user.email=a@b.c", "-c", "user.name=a", "commit", "-m", "init"], { cwd: path }); } return path; }
describe("ProjectContextService", () => {
  it("initializes a versioned git project and reuses clean context", () => { const path = repo(); const service = new ProjectContextService(); const first = service.open(path); const second = service.open(path); assert.ok(existsSync(join(path, ".cx", "project.json"))); assert.equal(first.metadata.rootPath.replaceAll("\\", "/"), path.replaceAll("\\", "/")); assert.equal(second.reindexed, false); assert.deepEqual(first.context.conventions, ["AGENTS.md instructions apply"]); });
  it("falls back to cwd, separates projects, and detects dirty changes", () => { const one = repo(true), two = repo(false); const service = new ProjectContextService(); const a = service.open(one), b = service.open(two); assert.notEqual(a.metadata.projectId, b.metadata.projectId); writeFileSync(join(one, "README.md"), "changed"); assert.equal(service.open(one).reindexed, true); });
  it("updates after a commit and allows forced reindexing", () => { const path = repo(); const service = new ProjectContextService(); service.open(path); writeFileSync(join(path, "README.md"), "new"); execFileSync("git", ["add", "."], { cwd: path }); execFileSync("git", ["-c", "user.email=a@b.c", "-c", "user.name=a", "commit", "-m", "readme"], { cwd: path }); assert.equal(service.open(path).reindexed, true); assert.equal(service.open(path, true).reindexed, true); });
  it("recovers cleanly from corrupt context and persists thread selection", () => { const path = repo(); const service = new ProjectContextService(); const first = service.open(path); first.threads.activeThreadId = "thread-1"; first.threads.threads.push({ threadId: "thread-1", createdAt: "now", lastUsedAt: "now", status: "active" }); service.saveThreads(path, first.threads); assert.equal(service.open(path).threads.activeThreadId, "thread-1"); writeFileSync(join(path, ".cx", "context.json"), "not json"); assert.equal(service.open(path).context.schemaVersion, 1); });
  it("keeps envelopes compact and excludes secret-like paths", () => { const path = repo(); for (const name of ["node_modules", "build", "dist"]) mkdirSync(join(path, name)); writeFileSync(join(path, ".env"), "SECRET=x"); writeFileSync(join(path, ".env.local"), "LOCAL=x"); writeFileSync(join(path, "private.key"), "key"); const service = new ProjectContextService(); const snapshot = service.open(path); const envelope = service.envelope(snapshot); const text = JSON.stringify(envelope); assert.equal(text.includes("SECRET"), false); assert.equal(text.includes("LOCAL"), false); assert.equal(text.includes("private.key"), false); assert.equal(text.includes("node_modules"), false); assert.ok(text.length < 4000); assert.equal(JSON.parse(readFileSync(join(path, ".cx", "context.json"), "utf8")).agentsInstructions, undefined); });
});
